media:
  - name: carousels
    label: carousels
    input: media/images/carousels
    output: /media/images/carousels

content:
  - name: carousels
    label: carousels
    type: collection
    path: carousels
    fields:
      - name: title
        type: string
      - name: description
        type: rich-text
      - name: link
        type: string
      - name: imgUrl
        type: string
      - name: image
        label: Cover image
        type: image
        options:
          media: carousels
          path: /media/images/carousels
      - name: buttonAction
        type: select
        options: 
          values: [Send an Email, Donate,Watch on YouTube, Listen on Spotify]  
      - name: active
        type: boolean
        default: true
  - name: campaigns
    label: campaigns
    type: collection
    path: campaigns
    fields:
      - name: title
        type: string
      - name: description
        type: rich-text
      - name: link
        type: string
      - name: imgUrl
        type: string
      - name: buttonAction
        type: select
        options: 
          values: [Send an Email, Donate,Watch on YouTube, Listen on Spotify]
      - name: active
        type: boolean
        default: true
  - name: donations
    label: donations
    type: collection
    path: donations
    fields:
      - name: name
        type: string
      - name: description
        type: rich-text
      - name: link
        type: string
      - name: imgUrl
        type: string
      - name: buttonAction
        type: select
        options: 
          values: [Send an Email, Donate,Watch on YouTube, Listen on Spotify]  
      - name: active
        type: boolean
        default: true
  - name: events
    label: events
    type: collection
    path: events
    fields:
      - name: id
        type: number
      - name: title
        type: string
      - name: description
        type: rich-text
      - name: link
        type: string
      - name: date
        type: date
        default: ""
        options:
        time: true
        format: dd-MM-yyyy'T'HH:mm
      - name: location
        type: string
