media:
  - name: carousels
    label: carousels
    input: media/images/carousels
    output: /media/images/carousels
  - name: campaigns
    label: campaigns
    input: media/images/campaigns
    output: /media/images/campaigns
  - name: donations
    label: donations
    input: media/images/donations
    output: /media/images/donations

content:
  - name: carousels
    label: carousels
    type: file
    path: carousels/data.json
    format: json
    list: true
    fields:
      - name: title
        type: string
      - name: description
        type: rich-text
      - name: link
        type: string
      - name: image
        label:  image (image name with out spcaes and special characters only underscore allowed)
        type: image
        options:
          media: carousels
          path: /media/images/carousels
      - name: buttonAction
        type: select
        options: 
          values: [Send an Email, Donate,Watch on YouTube, Listen on Spotify, Read More]
      - name: active
        type: boolean
        default: true
  - name: campaigns
    label: campaigns
    type: file
    path: campaigns/data.json
    format: json
    list: true
    fields:
      - name: title
        type: string
      - name: description
        type: rich-text
      - name: link
        type: string
      - name: image
        label:  image (image name with out spcaes and special characters only underscore allowed)
        type: image
        options:
          media: campaigns
          path: /media/images/campaigns
      - name: buttonAction
        type: select
        options: 
          values: [Send an Email, Donate,Watch on YouTube, Listen on Spotify, Read More]
      - name: active
        type: boolean
        default: true
  - name: donations
    label: donations
    type: file
    path: donations/data.json
    format: json
    list: true
    fields:
      - name: id
        type: number
      - name: name
        type: string
      - name: description
        type: rich-text
      - name: link
        type: string
      - name: image
        label:  image (image name with out spcaes and special characters only underscore allowed)
        type: image
        options:
          media: donations
          path: /media/images/donations
      - name: buttonAction
        type: select
        options: 
          values: [Send an Email, Donate,Watch on YouTube, Listen on Spotify, Read More]  
      - name: active
        type: boolean
        default: true
  - name: events
    label: events
    type: file
    path: events/data.json
    format: json
    list: true
    fields:
      - name: id
        type: number
      - name: title
        type: string
      - name: description
        type: rich-text
      - name: link
        type: string
      - name: date
        type: date
        default: ""
        options:
          time: true 
          format: yyyy-MM-dd'T'HH:mm
      - name: location
        type: string
